name: CI Pipeline

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore OrderProcessing/OrderProccessing.sln

    - name: Build the application
      run: dotnet build OrderProcessing/OrderProccessing.sln --no-restore

    - name: Run tests
      run: dotnet test OrderProcessing.Tests/OrderProcessing.Tests.csproj --no-build --verbosity normal
